rules:
  preset-smarthr: true
plugins:
  "@textlint/markdown":
    extensions:
      - ".md"
  jsx:
    extensions:
      - ".js"
      - ".ts"
      - ".jsx"
      - ".tsx"
filters:
  allowlist:
    allow:
      - ":::" # directiveの記法が「文末が"。"で終わっていません」に抵触してしまうのを防ぐ
      - "健康保険・厚生年金保険 被保険者賞与支払届" # content/04_リリースノート/02_届出書類（β公開中）のリリースノート/2022-05-31/ja.md で利用中。正式な書類名なのでルールを適用しない
      - "健康保険・厚生年金保険 被保険者報酬月額算定基礎届" # content/04_リリースノート/02_届出書類（β公開中）のリリースノート/2022-06-07/ja.md で利用中。正式な書類名なのでルールを適用しない
      - "健康保険・厚生年金保険 被保険者報酬月額変更届" # content/04_リリースノート/02_届出書類（β公開中）のリリースノート/2022-06-07/ja.md で利用中。正式な書類名なのでルールを適用しない
      - "おまかせ はたラクサポート" #サービスの固有名詞なのでルールを適用しない。
